### ISSUE TITLE
#2 기도카드 도착 뷰

### ISSUE THREAD

**Issue by eunjin3786** [ProjectInTheClass/TTBox2#1]
PraycardArr 에 기도카드 데이터를 임의로 넣어두었어요!
RandomCardViewController가 관리하는 뷰에 PraycardArr에 담긴 element(praycard) 2개를 꺼내서 이름,카테고리,내용을 뿌려주세요!

**Comment by msukang** [comment]
내용을 RansomCardViewController에 뿌렸습니다.

359122bfb89bc043185a821093b4128528a0028d
